export const TOOL_CATEGORIES = [
  'Converters',
  'Generators',
  'Text Tools',
  'Developer Tools',
  'Image Tools',
  'Calculators',
  'Productivity & Organizers',
  'Security & Crypto',
  'Data & Files',
  'AI Tools',
];

export const TOOL_DEFS = [
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert length, mass, temperature, time, and data units.',
    keywords: 'length mass temperature time data convert',
    category: 'Converters',
    icon: 'code',
    inputType: 'number',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/unit-converter.js'),
  },
  {
    id: 'base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, decimal, and hex.',
    keywords: 'binary decimal hex base',
    category: 'Converters',
    icon: 'braces',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/base-converter.js'),
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human time and back.',
    keywords: 'unix epoch time timezone',
    category: 'Converters',
    icon: 'code',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/timestamp-converter.js'),
  },
  {
    id: 'text-encoding',
    name: 'Text Encoding Converter',
    description: 'Base64, URL, and HTML encoding/decoding.',
    keywords: 'base64 url html encode decode',
    category: 'Converters',
    icon: 'code',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/text-encoding.js'),
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Create secure random passwords with custom rules.',
    keywords: 'password random secure',
    category: 'Generators',
    icon: 'key',
    inputType: 'none',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/password-generator.js'),
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4 values in bulk.',
    keywords: 'uuid v4 random',
    category: 'Generators',
    icon: 'fingerprint',
    inputType: 'none',
    supportsCopy: true,
    supportsDownload: true,
    loader: () => import('./modules/uuid-generator.js'),
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create QR codes offline in your browser.',
    keywords: 'qr code generator',
    category: 'Generators',
    icon: 'code',
    inputType: 'text',
    supportsCopy: false,
    supportsDownload: true,
    loader: () => import('./modules/qr-generator.js'),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Switch between common text casing styles.',
    keywords: 'lower upper title sentence camel snake kebab',
    category: 'Text Tools',
    icon: 'code',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/case-converter.js'),
  },
  {
    id: 'remove-duplicates',
    name: 'Remove Duplicate Lines',
    description: 'Deduplicate text lines with smart options.',
    keywords: 'unique lines dedupe',
    category: 'Text Tools',
    icon: 'code',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/remove-duplicates.js'),
  },
  {
    id: 'sort-lines',
    name: 'Sort Lines',
    description: 'Sort lines alphabetically or numerically.',
    keywords: 'sort lines asc desc',
    category: 'Text Tools',
    icon: 'code',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/sort-lines.js'),
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and minify JSON.',
    keywords: 'json format validate minify',
    category: 'Developer Tools',
    icon: 'braces',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: true,
    loader: () => import('./modules/json-formatter.js'),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT header and payload (no verification).',
    keywords: 'jwt decode token',
    category: 'Developer Tools',
    icon: 'fingerprint',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/jwt-decoder.js'),
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer & Compressor',
    description: 'Resize and compress images locally.',
    keywords: 'image resize compress jpg png webp',
    category: 'Image Tools',
    icon: 'palette',
    inputType: 'file',
    supportsCopy: false,
    supportsDownload: true,
    loader: () => import('./modules/image-resizer.js'),
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Solve common percentage questions quickly.',
    keywords: 'percent percentage math',
    category: 'Calculators',
    icon: 'braces',
    inputType: 'number',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/percentage-calculator.js'),
  },
  {
    id: 'date-diff',
    name: 'Date Difference Calculator',
    description: 'Calculate time between two dates.',
    keywords: 'date diff days hours minutes',
    category: 'Calculators',
    icon: 'braces',
    inputType: 'date',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/date-diff.js'),
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro Timer',
    description: 'Focused work sprints with breaks.',
    keywords: 'pomodoro timer focus',
    category: 'Productivity & Organizers',
    icon: 'code',
    inputType: 'none',
    supportsCopy: false,
    supportsDownload: false,
    loader: () => import('./modules/pomodoro.js'),
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-256 or SHA-512 hashes.',
    keywords: 'hash sha256 sha512 crypto',
    category: 'Security & Crypto',
    icon: 'hash',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/hash-generator.js'),
  },
  {
    id: 'csv-json',
    name: 'CSV ↔ JSON Converter',
    description: 'Convert CSV to JSON and JSON to CSV.',
    keywords: 'csv json convert',
    category: 'Data & Files',
    icon: 'braces',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: true,
    loader: () => import('./modules/csv-json.js'),
  },
  {
    id: 'prompt-builder',
    name: 'Prompt Template Builder',
    description: 'Build structured prompts offline.',
    keywords: 'prompt ai template',
    category: 'AI Tools',
    icon: 'code',
    inputType: 'text',
    supportsCopy: true,
    supportsDownload: false,
    loader: () => import('./modules/prompt-builder.js'),
  },
];

export function buildToolIndex(toolDefs = TOOL_DEFS) {
  return toolDefs.map(tool => {
    const hay = [tool.name, tool.description, tool.keywords, tool.category]
      .filter(Boolean)
      .join(' ')
      .toLowerCase();
    return { id: tool.id, hay };
  });
}
